 FROM python:3
 ENV PYTHONUNBUFFERED 1
 RUN mkdir /code
 WORKDIR /code
 ADD requirements.txt /code/
 RUN pip install -r requirements.txt
 ADD . /code/
 COPY /dockers/entrypoint.sh /entrypoint.sh
 RUN chmod +x /entrypoint.sh